//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutomationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppoinmentId { get; set; }
        public string AppointmentSubject { get; set; }
        public string AppointmentDescription { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int SlotId { get; set; }
        public string AppointmentStatus { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
