//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutomationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyMessage
    {
        public int ReplyMessageID { get; set; }
        public int ReplySenderID { get; set; }
        public int ReplyRecevierID { get; set; }
        public string MessageSubject { get; set; }
        public string MessageDescription { get; set; }
        public System.DateTime MessageDate { get; set; }
        public int MessageID { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
